github.com:
    users:
        aviral556:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: aviral556
